fx_version 'cerulean'
game "gta5"

this_is_a_map 'yes'

--- If the map includes custom props, you will need to add the ytyp name below for them to appear in your FiveM server ---
--- Simply uncomment the lines below and replace the quoted ytyp. ---


data_file "DLC_ITYP_REQUEST" "stream/*.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/*.ydr"
data_file "DLC_ITYP_REQUEST" "stream/*.ytd"
 
data_file "DLC_ITYP_REQUEST" "stream/downtown_01_metadata_007_strm.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/bkr_biker_dlc_int_02.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/v_int_61.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/v_int_68.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/ch_chint03_dlc_plan.ytd"
data_file "DLC_ITYP_REQUEST" "stream/ch_chint03_tool_box_01a.ydr"
data_file "DLC_ITYP_REQUEST" "stream/cs1_11_build1.ytd"
data_file "DLC_ITYP_REQUEST" "stream/cs1_11_tentcity09.ydr"
data_file "DLC_ITYP_REQUEST" "stream/cs4_10_detail.ytd"
data_file "DLC_ITYP_REQUEST" "stream/cs4_10_fnc_wire.ydr"
data_file "DLC_ITYP_REQUEST" "stream/index.html"
data_file "DLC_ITYP_REQUEST" "stream/int_medical.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/int_retail.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/lr_supermod_banners004.ydr"
data_file "DLC_ITYP_REQUEST" "stream/lr_supermod_banners2.ydr"
data_file "DLC_ITYP_REQUEST" "stream/lr_supermod_txd.ytd"
data_file "DLC_ITYP_REQUEST" "stream/tr_prop_tr_sign_gf_mr_01a.ydr"
data_file "DLC_ITYP_REQUEST" "stream/tr_prop_tr_sign_gf.ytd"
data_file "DLC_ITYP_REQUEST" "stream/v_54_lesters_txd.ytd"
data_file "DLC_ITYP_REQUEST" "stream/v_54_lng_mesh_maindesk.ydr"
data_file "DLC_ITYP_REQUEST" "stream/v_med_barrel.ydr"
data_file "DLC_ITYP_REQUEST" "stream/v_med_bed2.ydr"
data_file "DLC_ITYP_REQUEST" "stream/v_med_bench2.ydr"
data_file "DLC_ITYP_REQUEST" "stream/xm3_dlc_int_03_xm3.ydr"
data_file "DLC_ITYP_REQUEST" "stream/v_int_54.ydr"
data_file "DLC_ITYP_REQUEST" "stream/lr_supermod_garage_int.ydr"
data_file "DLC_ITYP_REQUEST" "stream/country_01_metadata_003_strm.ydr"
data_file "DLC_ITYP_REQUEST" "stream/ch_dlc_int_03_ch.ydr"

data_file "DLC_ITYP_REQUEST" "stream/apa_v_16_high_txd.ytd"
data_file "DLC_ITYP_REQUEST" "stream/country_04_metadata_003_strm.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/cs4_06_build_6.ydr"
data_file "DLC_ITYP_REQUEST" "stream/cs4_06_build2.ytd"
data_file "DLC_ITYP_REQUEST" "stream/cs4_06_build2+hi.ytd"
data_file "DLC_ITYP_REQUEST" "stream/cs4_06_build2a.ytd"
data_file "DLC_ITYP_REQUEST" "stream/cs4_06_build2a+hi.ytd"
data_file "DLC_ITYP_REQUEST" "stream/hei_v_16_high_txd.ytd"
data_file "DLC_ITYP_REQUEST" "stream/hei_v_16_high_txd+hi.ytd"
data_file "DLC_ITYP_REQUEST" "stream/int_club.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/int_residential.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/lr_cs4_06_build2.ytd"
data_file "DLC_ITYP_REQUEST" "stream/lr_cs4_06_build2+hi.ytd"
data_file "DLC_ITYP_REQUEST" "stream/v_15_carshowroom.ytd"
data_file "DLC_ITYP_REQUEST" "stream/v_15_carshowroom_rproxy.ydr"
data_file "DLC_ITYP_REQUEST" "stream/v_15_carshowroom+hi.ytd"
data_file "DLC_ITYP_REQUEST" "stream/v_15_shrm_mesh_desk.ydr"
data_file "DLC_ITYP_REQUEST" "stream/v_16_high_pln_m_map.ydr"
data_file "DLC_ITYP_REQUEST" "stream/v_16_high_txd.ytd"
data_file "DLC_ITYP_REQUEST" "stream/v_16_high_txd+hi.ytd"
data_file "DLC_ITYP_REQUEST" "stream/v_club_officesofa.ydr"
data_file "DLC_ITYP_REQUEST" "stream/v_club_officesofa+hidr.ytd"
data_file "DLC_ITYP_REQUEST" "stream/v_int_15.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/v_int_16.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/v_res_fh_barcchair.ydr"

data_file "DLC_ITYP_REQUEST" "stream/hw1_01_b+hidr.ytd"
data_file "DLC_ITYP_REQUEST" "stream/hei_hw1_01_b+hidr.ytd"

data_file "DLC_ITYP_REQUEST" "stream/barraco1.ydr"
data_file "DLC_ITYP_REQUEST" "stream/barraco2.ydr"
data_file "DLC_ITYP_REQUEST" "stream/barraco3.ydr"
data_file "DLC_ITYP_REQUEST" "stream/barraco4.ydr"
data_file "DLC_ITYP_REQUEST" "stream/barraco5.ydr"
data_file "DLC_ITYP_REQUEST" "stream/barraco6.ydr"
data_file "DLC_ITYP_REQUEST" "stream/barraco7.ydr"
data_file "DLC_ITYP_REQUEST" "stream/barraco8.ydr"
data_file "DLC_ITYP_REQUEST" "stream/barraco9.ydr"
data_file "DLC_ITYP_REQUEST" "stream/barraco10.ydr"
data_file "DLC_ITYP_REQUEST" "stream/barraco11.ydr"
data_file "DLC_ITYP_REQUEST" "stream/barraco12.ydr"
data_file "DLC_ITYP_REQUEST" "stream/barraco13.ydr"
data_file "DLC_ITYP_REQUEST" "stream/barraco14.ydr"
data_file "DLC_ITYP_REQUEST" "stream/barraco15.ydr"
data_file "DLC_ITYP_REQUEST" "stream/barraco16.ydr"
data_file "DLC_ITYP_REQUEST" "stream/bikini_map.ydr"
data_file "DLC_ITYP_REQUEST" "stream/hei_lev_des_mp_dlc.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/barraco15.ytd"
data_file "DLC_ITYP_REQUEST" "stream/hei_prop_heist_pics.ytd"
data_file "DLC_ITYP_REQUEST" "stream/hei_prop_hei_keypad_01.ytd"
 
 
 
